[package]
name = "ownership_passing"
version = "0.1.0"
authors = ["John Gallagher <jgallagher@bignerdranch.com>"]

[lib]
name = "ownership_passing"
crate-type = ["staticlib"]

[dependencies]
libc = "0.1"
